# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- sync
- prepare
- build-images
- fixtures
- lint
- test
- post-test
- review
- qa
- post-qa
- pages
- notify
default:
  image: registry.gitlab.com/gitlab-org/gitlab-build-images:ruby-2.7.patched-golang-1.16-git-2.33-lfs-2.9-chrome-89-node-14.15-yarn-1.22-postgresql-11-graphicsmagick-1.3.36
  tags:
  - gitlab-org
  interruptible: true
  timeout: 90m
workflow:
  rules:
  - if: "$FORCE_GITLAB_CI"
  - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^release-tools\/\d+\.\d+\.\d+-rc\d+$/
      && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^[\d-]+-stable(-ee)?$/ && $CI_PROJECT_PATH
      == "gitlab-org/gitlab"
    when: never
  - if: $CI_MERGE_REQUEST_EVENT_TYPE == "merged_result" || $CI_MERGE_REQUEST_EVENT_TYPE
      == "merge_train"
    variables:
      QA_IMAGE: "${CI_REGISTRY}/${CI_PROJECT_PATH}/gitlab-ee-qa:${CI_MERGE_REQUEST_SOURCE_BRANCH_SHA}"
  - if: "$CI_MERGE_REQUEST_IID"
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "schedule"
      && $FREQUENCY == "2-hourly"
    variables:
      CRYSTALBALL: 'true'
  - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
  - if: "$CI_COMMIT_TAG"
  - if: "$GITLAB_INTERNAL == null"
    when: never
  - if: "$CI_COMMIT_BRANCH =~ /^[\\d-]+-stable(-ee)?$/"
  - if: "$CI_COMMIT_BRANCH =~ /^\\d+-\\d+-auto-deploy-\\d+$/"
  - if: "$CI_COMMIT_BRANCH =~ /^security\\//"
variables:
  RAILS_ENV: test
  NODE_ENV: test
  BUNDLE_WITHOUT: production:development
  BUNDLE_INSTALL_FLAGS: "--jobs=$(nproc) --retry=3 --quiet"
  NODE_OPTIONS: "--max_old_space_size=3584"
  GIT_DEPTH: '20'
  GIT_SUBMODULE_STRATEGY: none
  GET_SOURCES_ATTEMPTS: '3'
  KNAPSACK_RSPEC_SUITE_REPORT_PATH: knapsack/report-master.json
  FLAKY_RSPEC_SUITE_REPORT_PATH: rspec_flaky/report-suite.json
  RSPEC_TESTS_MAPPING_PATH: crystalball/mapping.json
  RSPEC_PACKED_TESTS_MAPPING_PATH: crystalball/packed-mapping.json
  FRONTEND_FIXTURES_MAPPING_PATH: crystalball/frontend_fixtures_mapping.json
  ES_JAVA_OPTS: "-Xms256m -Xmx256m"
  ELASTIC_URL: http://elastic:changeme@elasticsearch:9200
  DOCKER_VERSION: 20.10.1
  CACHE_CLASSES: 'true'
  CHECK_PRECOMPILED_ASSETS: 'true'
  FF_USE_FASTZIP: 'true'
  DOCS_REVIEW_APPS_DOMAIN: 178.62.207.141.nip.io
  DOCS_GITLAB_REPO_SUFFIX: ee
  REVIEW_APPS_DOMAIN: gitlab-review.app
  REVIEW_APPS_GCP_PROJECT: gitlab-review-apps
  REVIEW_APPS_GCP_REGION: us-central1
  BUILD_ASSETS_IMAGE: 'true'
  SIMPLECOV: 'true'
  QA_IMAGE: "${CI_REGISTRY}/${CI_PROJECT_PATH}/gitlab-ee-qa:${CI_COMMIT_SHA}"
  QA_IMAGE_BRANCH: "${CI_REGISTRY}/${CI_PROJECT_PATH}/gitlab-ee-qa:${CI_COMMIT_REF_SLUG}"
  GIT_CLONE_PATH: "/builds/gitlab-org-forks/${CI_PROJECT_NAME}"
include:
- local: ".gitlab/ci/*.gitlab-ci.yml"
- remote: https://gitlab.com/gitlab-org/frontend/untamper-my-lockfile/-/raw/main/.gitlab-ci-template.yml
- template: Security/Dependency-Scanning.gitlab-ci.yml
