stages:
  - sync
  - prepare
  - build-images
  - fixtures
  - test
  - post-test
  - review-prepare
  - review
  - dast
  - qa
  - post-qa
  - pages
  - notify

.base-before_script: &base-before_script
  - source ./scripts/utils.sh
  - source ./scripts/review_apps/review-apps.sh
  - install_api_client_dependencies_with_apk

kubectl-version:
  extends:
    - .review-workflow-base
  stage: test
  image: registry.gitlab.com/gitlab-org/gitlab-build-images:gitlab-helm3-kubectl1.14
  needs: []
  resource_group: "review/${CI_COMMIT_REF_NAME}"
  before_script:
    - echo ${CI_PRE_CLONE_SCRIPT}
    - kubectl version
    - export GITLAB_SHELL_VERSION=$(<GITLAB_SHELL_VERSION)
    - export GITALY_VERSION=$(<GITALY_SERVER_VERSION)
    - export GITLAB_WORKHORSE_VERSION=$(<GITLAB_WORKHORSE_VERSION)
    - echo "${CI_ENVIRONMENT_URL}" > environment_url.txt
    - *base-before_script
  script:
    - which kubectl
    - kubectl version --client
    - kubectl version
    - check_kube_domain
    - ensure_namespace
    - install_external_dns
    - download_chart
    - kubectl version
    - date
    - deploy || (display_deployment_debug && exit 1)
    - disable_sign_ups || (delete_release && exit 1)
    # When the job is manual, review-qa-smoke is also manual and we don't want people
    # to have to manually start the jobs in sequence, so we do it for them.
    - '[ -z $CI_JOB_MANUAL ] || scripts/api/play_job.rb --job-name "review-qa-smoke"'
    - '[ -z $CI_JOB_MANUAL ] || scripts/api/play_job.rb --job-name "review-performance"'

variables:
  GIT_DEPTH: "20"
  GIT_SUBMODULE_STRATEGY: "none"

include:
  - local: .gitlab/ci/global.gitlab-ci.yml
  - local: .gitlab/ci/review.gitlab-ci.yml
  - local: .gitlab/ci/rules.gitlab-ci.yml
  - local: .gitlab/ci/frontend.gitlab-ci.yml
  - local: .gitlab/ci/rails.gitlab-ci.yml
  - local: .gitlab/ci/test-metadata.gitlab-ci.yml
  - local: .gitlab/ci/setup.gitlab-ci.yml
  - local: .gitlab/ci/memory.gitlab-ci.yml
