---
name: blobless_diff_highlighting
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/53825
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/323566
milestone: '13.10'
type: development
group: group::source code
default_enabled: true
