---
name: broadcast_issuable_description_updated
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/98458
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/375183
milestone: '15.5'
type: development
group: group::project management
default_enabled: false
