---
name: cached_issuables_state_count
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/63549
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/333089
milestone: '14.0'
type: development
group: group::project management
default_enabled: false
