---
name: ci_job_artifacts_cdn
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/98010
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/373860
milestone: '15.5'
type: development
group: group::pipeline execution
default_enabled: false
