---
name: ci_remove_userless_ci
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/92942
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/368427
milestone: '15.5'
type: development
group: group::pipeline execution
default_enabled: false
