---
name: destroy_only_cancelled_pipelines
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/65559
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/335319
milestone: '14.1'
type: development
group: group::continuous integration
default_enabled: false
