---
name: email_for_two_factor_otp_failure
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/98507
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/374741
milestone: '15.5'
type: development
group: group::authentication and authorization
default_enabled: false
