---
name: environments_search
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/97015
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/372541
milestone: '15.4'
type: development
group: group::release
default_enabled: false
