---
name: graphql_ci_job_trace
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/50039
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/294004
milestone: '13.8'
type: development
group: group::verify
default_enabled: true
