---
name: markdown_corrected_blockquote
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/95967
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/372089
milestone: '15.4'
type: development
group: group::project management
default_enabled: false
