---
name: mobile_devops_settings
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/97548
rollout_issue_url:
milestone: '15.4'
type: development
group: group::incubation
default_enabled: false
