---
name: namespace_details_feature_flag
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/82958
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/360728
milestone: '15.0'
type: development
group: group::workspace
default_enabled: false
