---
name: new_form_errors
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/54844
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/323619
milestone: '14.5'
type: development
group: group::container security
default_enabled: false
