---
name: remove_user_attributes
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/96447
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/372047
milestone: '15.4'
type: development
group: group::code review
default_enabled: false
