---
name: runners_finder_all_available
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/96770
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/374525
milestone: '15.5'
type: development
group: group::runner
default_enabled: false
