---
name: use_inherited_permissions_for_approval_rules
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/92659
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/368117
milestone: '15.2'
type: development
group: group::source code
default_enabled: false
