---
name: use_content_type_from_filename
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/93617
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/370163
milestone: '15.3'
type: development
group: group::source code
default_enabled: false
