---
name: vue_broadcast_messages
introduced_by_url: "https://gitlab.com/gitlab-org/gitlab/-/merge_requests/98127"
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/368847
milestone: '15.4'
type: development
group: group::optimize
default_enabled: false
