---
name: corpus_management_ui
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/77279
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/349014
milestone: '14.8'
type: development
group: group::dynamic analysis
default_enabled: true