---
key_path: redis_hll_counters.terraform.p_terraform_state_api_unique_users_weekly
description: 'Weekly active users of GitLab Managed Terraform state'
product_section: 'ops'
product_stage: 'configure'
product_group: 'configure'
product_category: 'Infrastructure as Code'
value_type: number
status: data_available
time_frame: 7d
data_source: redis_hll
distribution:
- ee
tier: []
skip_validation: false
