---
key_path: redis_hll_counters.ci_secrets_management.i_ci_secrets_management_vault_build_created_weekly
description: 'MAU metric for configured Vault JWT access token'
product_section: 'ops'
product_stage: 'configure'
product_group: 'configure'
product_category: 'Secrets Management'
value_type: number
status: data_available
time_frame: 7d
data_source: redis_hll
distribution:
- ee
tier: []
skip_validation: true
