---
key_path: redis_hll_counters.terraform.p_terraform_state_api_unique_users_monthly
description: 'MAU metric for GitLab Managed Terraform state'
product_section: 'ops'
product_stage: 'configure'
product_group: 'configure'
product_category: 'Infrastructure as Code'
value_type: number
status: data_available
time_frame: 28d
data_source: redis_hll
distribution:
- ce
tier:
- free
skip_validation: false
